### ISSUE TITLE
Unable to download all the YouTube videos

### ISSUE THREAD

**Issue by fazliimam** [minghu0830/NurViD-benchmark#2]
Unable to download all the youtube videos.
Failed to download 517 of the videos. 
Is it possible for you to provide all the downloaded videos for direct download?

**Comment by minghu0830** [comment]
Sorry for the late reply. As some YouTube video creators have deleted their videos making them unavailable for download, we have updated the download link. Please submit the [data agreement form](https://form.jotform.com/232158342596158) again.

**Comment by fazliimam** [comment]
Thank you @minghu0830

**Comment by fazliimam** [comment]
@minghu0830 is it possible for you to share the audio subtitles files if available?

**Comment by minghu0830** [comment]
Yes. When we used the yt-dlp library to crawl videos, we also automatically generated subtitles, but not all videos have them. It seems that only about 2/3 of the videos have subtitle files. If you need them, I can share them with you after I finish organizing them soon. @fazlicodes
