### ISSUE TITLE
procedureID not found in NurViD_annotations.json

### ISSUE THREAD

**Issue by fazliimam** [minghu0830/NurViD-benchmark#3]
When running the clip.py file, I got the following error:
`File "NurViD-benchmark/tools/clip.py", line 25, in <module>
    operation_id = data[video_name]["procedureID"]
KeyError: 'procedureID`

**Comment by minghu0830** [comment]
Thank you for your correction. You only need to replace the "procedureID" on [line 25](https://github.com/minghu0830/NurViD-benchmark/blob/main/tools/clip.py#25) of clip.py with "operationID".
